### PR TITLE
Various Fixes

### PR DESCRIPTION
**Pull request by DogsGoBark**
- Adjusted the paths to `client/x.lua` and `server/x.lua`.
- Adjusted the `fxmanifest.lua` to be properly in order.
- Replaced all `GetPlayerPed(-1)` with `PlayerPedId()`
- Removed duplicate `/e` chat suggestion from menu.
- Removed random space in Keybinds.
- Removed random spaces in AnimationList.
- Added /walk fix from the original repository.

**Notes**: People can use these emotes to glitch through walls.
```lua
   ["sunbathe3"] = {"Scenario", "WORLD_HUMAN_SUNBATHE", "Sunbathe 3"},
   ["sunbatheback"] = {"Scenario", "WORLD_HUMAN_SUNBATHE_BACK", "Sunbathe Back"},
```

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
If players are wall breaching or breaking out of handcuffs via using emotes, then I would kick them from the server for fail RP. There isn't exactly much you can do.

**Comment by DogsGoBark** [comment]
> If players are wall breaching or breaking out of handcuffs via using emotes, then I would kick them from the server for fail RP. There isn't exactly much you can do.

I didn't disable them, they're still enabled.

**Comment by TayMcKenzieNZ** [comment]
Thanks for your various fixes and additions!

**Comment by TayMcKenzieNZ** [comment]
Well, I don't know what you did, but before, animations with props worked fine, now they only work in chat commands ie /e beg. clicking beg from the menu does not play the animation.

**Comment by DogsGoBark** [comment]
Tried it on mine and it works fine?

**Comment by TayMcKenzieNZ** [comment]
They seem to be bugged if you're using a controller

**Comment by TayMcKenzieNZ** [comment]
Personally I change F3 to F5 because of controller, but prop gets attached and animation doesn't perform 🤔

**Comment by DogsGoBark** [comment]
> They seem to be bugged if you're using a controller
> Personally I change F3 to F5 because of controller, but prop gets attached and animation doesn't perform 🤔
That's strange I will look into it because my animations work fine and I am on Artifact 5122. I don't use controller so not sure.

**Comment by TayMcKenzieNZ** [comment]
I just updated artifacts too. Everything else is fine just controller, but perhaps menu is not made for controller input, as keyboard seems fine. I am not blaming you, just confused. Sorry 😔

**Comment by DogsGoBark** [comment]
> I just updated artifacts too. Everything else is fine just controller, but perhaps menu is not made for controller input, as keyboard seems fine. I am not blaming you, just confused. Sorry 😔

Maybe it can be ported over to MenuV which has controller support?

**Comment by TayMcKenzieNZ** [comment]
Possibly. When I reverted the changes, it was still bugged with controller 🤔

**Comment by TayMcKenzieNZ** [comment]
Anyways, again; thank you for your PR 🙂

**Pull request merged**
