### PR TITLE
Fix emote cancel scuff

### PR DESCRIPTION
**Pull request by FjamZoo**
This makes it so if the player is running 1 animation from dpemotes and 1 scenario from a 3rd script could be a sitting script it wont cancel the sitting but only the animation from dpemotes which is very helpful when trying to do stuff such as sitting and eating, sitting and people trynna glitch off the seat doing a mission or smt.

### CODE REVIEW

**Comment by FjamZoo** [comment]
Had to refork the thing so it deleted it lmao

**Comment by TayMcKenzieNZ** [comment]
I genuinely don't understand this and if people are using some other nonsense alongside DpEmotes then that's on them. Nothing is "scuffed". You can literally type /e sit then /e burger and do mixed emotes.

I won't be accepting this PR until I get a second opinion.

**Comment by AvaN0x** [comment]
Looking at the code changes, I can say for sure that there will be issues with it.
Example: start a sit emote, start an eating emote, try to cancel both of them
With the code you changed, it'll only cancel the eating emote with no way of stopping the sit emote.
(*Not tested but it should be the end result*)

**Comment by AvaN0x** [comment]
I'm not talking about a settings script, but for example start the conehead emote and then a laydown emote or smoke emote, you'll need to disable both of the emotes.
Dpemotes allows to start **multiple** emotes, not only one!

**Comment by TayMcKenzieNZ** [comment]
This seems a mess and unfortunately I won't be accepting this PR. Sorry.

**Comment by iSentrie** [comment]
> Dpemotes allows to start **multiple** emotes, not only one!

and that is amazing, that makes it even more fun and more variations can be made from calling different emotes :|

**Pull request closed without merging**
