### PR TITLE
Support for More emotes / Fix for FxManifest / Walkstick Item added

### PR DESCRIPTION
**Pull request by AnishBplayz**
We have added support to more Emotes / collection of our emotes from our server in this PR and have done some changes to the files mentioned below -

Added a WalkingStick item:
Edited ``walk.lua`` and ``server.lua`` for walkingstick animation (MORE QOL)

Also updated the ``Readme.md`` for the Walkstick item addition for qb-core

Regards [KudosRP](https://discord.gg/kudosrp)

Credits to - [AnishBplayz](https://github.com/AnishBplayz), [Jeay ](https://github.com/heyjeay/)

### CODE REVIEW

**Comment by AnishBplayz** [comment]
Fixed the Fxmanifest thing u mentioned.... I was confused due to the other dpemotes... apologies

**Comment by AnishBplayz** [comment]
good point, let me make some edits for fixing that...

**Comment by TayMcKenzieNZ** [comment]
This has become a mess lol

**Comment by AnishBplayz** [comment]
So I added a config.Framework == 'qb-core' check so this should even support the standalone part now...

**Comment by TayMcKenzieNZ** [comment]
This is a mess. I won't be accepting it. The ONLY thing that should be added in the PR is the added animations. Too many things have been changed, some minor improvements, some, not soo much. I'm not comfortable accepting this PR sorry.

**Pull request closed without merging**
