### PR TITLE
(qb-core) Add support for persistent walkstyles

### PR DESCRIPTION
**Pull request by crusopaul**
Currently walkstyle animations set by dpemotes will disappear when a ped is unloaded / reloaded. A common scenario where this occurs is on player logout / login - logging in does not apply the last set walkstyle.

This PR adds optional support to dpemotes for saving walkstyles that persist across player logout / login. I was not entirely sure what the future intention / direction of the Config.Framework is, and this PR was written for [qb-core](https://github.com/qbcore-framework/qb-core/), so this functionality only works on qb-core as written.

Functionality is achieved by adding a `walkstyle` column to the players table that is written to and read from upon player unload, load, and selection of a walkstyle.

### CODE REVIEW

**Comment by TayMcKenzieNZ** [comment]
Hello, thank you for your contribution.

Unfortunately, the framework part in the config was just to make the transfer to my fork from the qb's one possible, not to add anything on top of that. I'd prefer that DpEmotes remains standalone, however allows basic qb-core stuff to work, rather than adding all of the framework required stuff directly into DpEmotes;, perhaps it can still be achieved, but through kvs or KVP or whatever it's called? I was able to do something similar with idle cameras and when the player first joins the session, idle cam is on by default, until the player uses the chat command to turn it off, then, when the player logs onto ANY FiveM server with that resource, it reads the clients preference and goes, "ok, set it off", similarly, you can select your favourite radio stations to display in any FiveM server that has Smallo's resource 

https://forum.cfx.re/t/free-xnradio-gta-online-like-radio-favourites-build-2372-mptuner-dlc/4103031

**Comment by crusopaul** [comment]
I see - that makes sense! I had no idea KVP's existed 👀 I'd be interested in rewriting this to utilize those instead. At a cursory glance it looks like the only qb calls I utilize are for the read/write to the `walkstyle` field (which isn't required with KVP's.) Like you said, that would at least make this functionality independent from framework.

The only limitation of using KVP's seems that they are stored in %APPDATA%\Roaming\CitizenFX so if a player were to clean this folder, or use another device, then they would not load in with the expected walkstyle.

**Comment by TayMcKenzieNZ** [comment]
That is a valid point 🤔 however we can make that apparent. As of now, my understanding is that as long as the resource or string of code isn't renamed, it should work, so if I continue to o keep the name DpEmotes, it must be named that in all servers and in the server.cfg, or I need to come up with another name, then implement this code. 

I make regular back ups of that location you mentioned as I believe vMenu data is also stored here and I spent hours making my characters lol

**Comment by AvaN0x** [comment]
> The only limitation of using KVP's seems that they are stored in %APPDATA%\Roaming\CitizenFX so if a player were to clean this folder, or use another device, then they would not load in with the expected walkstyle.

image
All of the above are available server side too, you can use them there and we won't have the client side issue. :)
Unfortunately I never used them server side so I don't know where they are stored. 🤔

**Comment by TayMcKenzieNZ** [comment]
Ooh, yes! I remember discussing this!

https://forum.cfx.re/t/saving-variables-on-server-between-restarts/4891739

Sorry for the delay, I FINALLY found where I discussed it, ok so;

you have your choice of:

client-side: kvs

server-side: kvs

Client-side pros:

Will work on any server assuming they have the right version of this resource and it’s named exactly the same as you name it, the resource mustn’t be renamed.

Client-side cons:

If you get a new PC or use multiple PCs to play FiveM, you have to sync your AppData stuff, or you’ll lose your preferences.

Changing the resource’s name will result in players losing their preferences.

A malicious server could delete all their preferences with a fake resource named exactly the same thing.

Server-side pros:

No matter PC the player uses, as long as they have whatever identifier(s) (game license, Cfx account, Steam account, Discord account, Xbox Live account, etc.) you use to link them to their preferences, they won’t lose them.

You can change the name of the resource or virtually anything about the backend without players losing their preferences

Easy to use the data in other ways (what’s the most popular aim style on your server? Look it up in the database!)

Server-side cons:

Players will have to set their preferences on each server they play on (or at least each server run by different people)

For my Idle Cam script, I made it client side. Players can decide to turn it back on themselves on the servers they join, as long as that server has the current version of my script, and it hasn’t been renamed from NoIdleCam.

**Comment by AvaN0x** [comment]
> https://forum.cfx.re/t/saving-variables-on-server-between-restarts/4891739

In a `db` folder, nice to know :)

**Comment by TayMcKenzieNZ** [comment]
Yah! So I think you make a table and basically have it so that when you select a particular walkstyle, it automatically stores that preference, and you can leave the server and come back and you're still set in that walkstyle, you could even go further and do moods too

**Comment by crusopaul** [comment]
Oh awesome information!

I'm looking at this again and am noticing another issue... It looks like I was using qb-core's `QBCore:Client:OnPlayerLoaded` event to apply the walkstyle. I may have to get tricky with the native `gameEventTriggered` by using the event `CEventNetworkPlayerSpawn` to get this to work?

If possible, I'd also like to write this to support a multicharacter environment. I'll do some research on that...

Any opposition to potentially using a combination of client / server KVP's? I'm thinking it'd be best to do something like the following:
- Check client KVP for walkstyle existence - existence implies setting the walkstyle, otherwise the following server event is called
- A server event is called for KVP walkstyle existence - existence implies passing the walkstyle to a client event so that it may be set, otherwise no walkstyle is set

This avoids the issue of multiple devices / clearing roaming data for players causing missing walkstyles. It also allows players to preserve walkstyles across servers.

**Comment by TayMcKenzieNZ** [comment]
Sounds reasonable 🤔 that whole QBCore stuff is confusing and a headache however as they should technically be using ExecuteEvent or whatever

**Comment by TayMcKenzieNZ** [comment]
Are you able to make a new PR with just the KVP stuff? It gets a bit confusing with all the commits and the "add for qbcore, remove, add KVP" etc, lol sorry

**Comment by crusopaul** [comment]
I can do that haha - but I'll leave a link to the original PR. Closing with the intent of opening a new PR.

**Comment by TayMcKenzieNZ** [comment]
Sorry lol, we just like to keep all the commits clean so if anything was to go wrong we can pin point where lol

**Pull request closed without merging**
